sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: oFVRBh7ilMlW1HWsP63UnxD4UzClX1gJjHQ683KoVw7WEoujjgAXPNW2SZL3S38RJfnYznEl0DoOBNcFO8qh0EgZCFjq1w43N5L3IPEZ8XVC+5ITeDY9faLaflUQ/k4oYR5d+yR8xNFyv5Yvxm2+7QYlccozDS1+tze7yyzIuLgEPoksZLXXT7KZqbw84qe464dLZB9d+6xlW6UdPc6D01jnSLlIN1uFsdWlI2SNPboMRyyWrqg5WbviNFn5pErBieTtKeJZRhZlh3z+VZd5d7lPYbphkMclY9KkUbRllHrKZZzpP+HR9aqNe/mb+NER1Cc1tD/0uEIoqqxGlWWScZ3HdA6DeLhW+XI72Ml5RJGiz/l0boBhk4gNNc6/yW88G3yhaSwgFW3h5+gO+AuP2JoTkrcgXpqMvmf74KC11dBCWjP4CLunUCYxU5EYSijJ8lPYyhsAW/5B/4VRHXrE5U0dSoDQYeF1rzDHHsDEcPqY8iGLKpSlN7mScmJ+pHFRhiVSpnJ7uhZ8BY3TW2CUKl0ianqF9bmhlMsqDG3hJSfKMIVrz8Pg2bn4lQ+SzO1VzD1LJySTnBSt9th77Utg9cAbWicwktRqZVV+2ebtwpQSQwNuS9AOSK0Z6cKoU0uRmlWFdKleN3G/+1bo+kf5Tz2HM/QWLMKEgY4sRYJVzoo=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Openings-in-the-Old-Trail_2535
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy